version: '3.1'

services:
  study_app:
    build: .
#    command: tail -f /dev/null
    image: ruby_study:latest
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    volumes:
      - .:/lessons:cached
    entrypoint: ./entrypoints/entrypoint.sh



